# Generated by Django 6.0.2 on 2026-05-19 15:48

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("secure_notes", "0002_alter_note_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="content",
            field=encrypted_fields.fields.EncryptedTextField(),
        ),
    ]
